# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_secret_store_spec_provider_akeyless_auth_secret_ref_kubernetes_auth_secret_ref import IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthSecretRef
from .io_external_secrets_v1alpha1_secret_store_spec_provider_akeyless_auth_secret_ref_kubernetes_auth_service_account_ref import IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthServiceAccountRef
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuth(BaseModel):
    """
    Kubernetes authenticates with Akeyless by passing the ServiceAccount token stored in the named Secret resource.
    """ # noqa: E501
    access_id: StrictStr = Field(description="the Akeyless Kubernetes auth-method access-id", alias="accessID")
    k8s_conf_name: StrictStr = Field(description="Kubernetes-auth configuration name in Akeyless-Gateway", alias="k8sConfName")
    secret_ref: Optional[IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthSecretRef] = Field(default=None, alias="secretRef")
    service_account_ref: Optional[IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthServiceAccountRef] = Field(default=None, alias="serviceAccountRef")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["accessID", "k8sConfName", "secretRef", "serviceAccountRef"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of secret_ref
        if self.secret_ref:
            _dict['secretRef'] = self.secret_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_account_ref
        if self.service_account_ref:
            _dict['serviceAccountRef'] = self.service_account_ref.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "accessID": obj.get("accessID"),
            "k8sConfName": obj.get("k8sConfName"),
            "secretRef": IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthSecretRef.from_dict(obj["secretRef"]) if obj.get("secretRef") is not None else None,
            "serviceAccountRef": IoExternalSecretsV1alpha1SecretStoreSpecProviderAkeylessAuthSecretRefKubernetesAuthServiceAccountRef.from_dict(obj["serviceAccountRef"]) if obj.get("serviceAccountRef") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


