# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_generators_v1alpha1_acr_access_token_spec_auth_workload_identity_service_account_ref import IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthWorkloadIdentityServiceAccountRef
from .io_external_secrets_v1alpha1_secret_store_spec_provider_azurekv_auth_secret_ref import IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekvAuthSecretRef
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekv(BaseModel):
    """
    AzureKV configures this store to sync secrets using Azure Key Vault provider
    """ # noqa: E501
    auth_secret_ref: Optional[IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekvAuthSecretRef] = Field(default=None, alias="authSecretRef")
    auth_type: Optional[StrictStr] = Field(default=None, description="Auth type defines how to authenticate to the keyvault service. Valid values are: - \"ServicePrincipal\" (default): Using a service principal (tenantId, clientId, clientSecret) - \"ManagedIdentity\": Using Managed Identity assigned to the pod (see aad-pod-identity)", alias="authType")
    identity_id: Optional[StrictStr] = Field(default=None, description="If multiple Managed Identity is assigned to the pod, you can select the one to be used", alias="identityId")
    service_account_ref: Optional[IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthWorkloadIdentityServiceAccountRef] = Field(default=None, alias="serviceAccountRef")
    tenant_id: Optional[StrictStr] = Field(default=None, description="TenantID configures the Azure Tenant to send requests to. Required for ServicePrincipal auth type.", alias="tenantId")
    vault_url: StrictStr = Field(description="Vault Url from which the secrets to be fetched from.", alias="vaultUrl")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["authSecretRef", "authType", "identityId", "serviceAccountRef", "tenantId", "vaultUrl"]

    @field_validator('auth_type')
    def auth_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ServicePrincipal', 'ManagedIdentity', 'WorkloadIdentity']):
            raise ValueError("must be one of enum values ('ServicePrincipal', 'ManagedIdentity', 'WorkloadIdentity')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekv from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of auth_secret_ref
        if self.auth_secret_ref:
            _dict['authSecretRef'] = self.auth_secret_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_account_ref
        if self.service_account_ref:
            _dict['serviceAccountRef'] = self.service_account_ref.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekv from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "authSecretRef": IoExternalSecretsV1alpha1SecretStoreSpecProviderAzurekvAuthSecretRef.from_dict(obj["authSecretRef"]) if obj.get("authSecretRef") is not None else None,
            "authType": obj.get("authType"),
            "identityId": obj.get("identityId"),
            "serviceAccountRef": IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthWorkloadIdentityServiceAccountRef.from_dict(obj["serviceAccountRef"]) if obj.get("serviceAccountRef") is not None else None,
            "tenantId": obj.get("tenantId"),
            "vaultUrl": obj.get("vaultUrl")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


