# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from .io_external_secrets_v1beta1_secret_store_spec_provider_onboardbase_auth import IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbase(BaseModel):
    """
    Onboardbase configures this store to sync secrets using the Onboardbase provider
    """ # noqa: E501
    api_host: StrictStr = Field(description="APIHost use this to configure the host url for the API for selfhosted installation, default is https://public.onboardbase.com/api/v1/", alias="apiHost")
    auth: IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth
    environment: StrictStr = Field(description="Environment is the name of an environmnent within a project to pull the secrets from")
    project: StrictStr = Field(description="Project is an onboardbase project that the secrets should be pulled from")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiHost", "auth", "environment", "project"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbase from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of auth
        if self.auth:
            _dict['auth'] = self.auth.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbase from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiHost": obj.get("apiHost"),
            "auth": IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth.from_dict(obj["auth"]) if obj.get("auth") is not None else None,
            "environment": obj.get("environment"),
            "project": obj.get("project")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


