# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from .io_external_secrets_v1beta1_secret_store_spec_provider_onboardbase_auth_api_key_ref import IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthApiKeyRef
from .io_external_secrets_v1beta1_secret_store_spec_provider_onboardbase_auth_passcode_ref import IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthPasscodeRef
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth(BaseModel):
    """
    Auth configures how the Operator authenticates with the Onboardbase API
    """ # noqa: E501
    api_key_ref: IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthApiKeyRef = Field(alias="apiKeyRef")
    passcode_ref: IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthPasscodeRef = Field(alias="passcodeRef")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiKeyRef", "passcodeRef"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of api_key_ref
        if self.api_key_ref:
            _dict['apiKeyRef'] = self.api_key_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of passcode_ref
        if self.passcode_ref:
            _dict['passcodeRef'] = self.passcode_ref.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiKeyRef": IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthApiKeyRef.from_dict(obj["apiKeyRef"]) if obj.get("apiKeyRef") is not None else None,
            "passcodeRef": IoExternalSecretsV1beta1SecretStoreSpecProviderOnboardbaseAuthPasscodeRef.from_dict(obj["passcodeRef"]) if obj.get("passcodeRef") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


