# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1beta1_external_secret_spec_target_template_template_from_inner_config_map import IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInnerConfigMap
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInner(BaseModel):
    """
    IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInner
    """ # noqa: E501
    config_map: Optional[IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInnerConfigMap] = Field(default=None, alias="configMap")
    literal: Optional[StrictStr] = None
    secret: Optional[IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInnerConfigMap] = None
    target: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["configMap", "literal", "secret", "target"]

    @field_validator('target')
    def target_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Data', 'Annotations', 'Labels']):
            raise ValueError("must be one of enum values ('Data', 'Annotations', 'Labels')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config_map
        if self.config_map:
            _dict['configMap'] = self.config_map.to_dict()
        # override the default output from pydantic by calling `to_dict()` of secret
        if self.secret:
            _dict['secret'] = self.secret.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "configMap": IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInnerConfigMap.from_dict(obj["configMap"]) if obj.get("configMap") is not None else None,
            "literal": obj.get("literal"),
            "secret": IoExternalSecretsV1beta1ExternalSecretSpecTargetTemplateTemplateFromInnerConfigMap.from_dict(obj["secret"]) if obj.get("secret") is not None else None,
            "target": obj.get("target")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


