# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_generators_v1alpha1_gcr_access_token_spec_auth_secret_ref import IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthSecretRef
from .io_external_secrets_generators_v1alpha1_gcr_access_token_spec_auth_workload_identity import IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthWorkloadIdentity
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuth(BaseModel):
    """
    Auth defines the means for authenticating with GCP
    """ # noqa: E501
    secret_ref: Optional[IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthSecretRef] = Field(default=None, alias="secretRef")
    workload_identity: Optional[IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthWorkloadIdentity] = Field(default=None, alias="workloadIdentity")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["secretRef", "workloadIdentity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of secret_ref
        if self.secret_ref:
            _dict['secretRef'] = self.secret_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workload_identity
        if self.workload_identity:
            _dict['workloadIdentity'] = self.workload_identity.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "secretRef": IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthSecretRef.from_dict(obj["secretRef"]) if obj.get("secretRef") is not None else None,
            "workloadIdentity": IoExternalSecretsGeneratorsV1alpha1GCRAccessTokenSpecAuthWorkloadIdentity.from_dict(obj["workloadIdentity"]) if obj.get("workloadIdentity") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


