# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_external_secret_spec_secret_store_ref import IoExternalSecretsV1alpha1ExternalSecretSpecSecretStoreRef
from .io_external_secrets_v1beta1_external_secret_spec_data_inner_source_ref_generator_ref import IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRefGeneratorRef
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRef(BaseModel):
    """
    SourceRef allows you to override the source from which the value will pulled from.
    """ # noqa: E501
    generator_ref: Optional[IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRefGeneratorRef] = Field(default=None, alias="generatorRef")
    store_ref: Optional[IoExternalSecretsV1alpha1ExternalSecretSpecSecretStoreRef] = Field(default=None, alias="storeRef")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["generatorRef", "storeRef"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of generator_ref
        if self.generator_ref:
            _dict['generatorRef'] = self.generator_ref.to_dict()
        # override the default output from pydantic by calling `to_dict()` of store_ref
        if self.store_ref:
            _dict['storeRef'] = self.store_ref.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "generatorRef": IoExternalSecretsV1beta1ExternalSecretSpecDataInnerSourceRefGeneratorRef.from_dict(obj["generatorRef"]) if obj.get("generatorRef") is not None else None,
            "storeRef": IoExternalSecretsV1alpha1ExternalSecretSpecSecretStoreRef.from_dict(obj["storeRef"]) if obj.get("storeRef") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


