# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_external_secret_spec_target_template_metadata import IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateMetadata
from .io_external_secrets_v1alpha1_external_secret_spec_target_template_template_from_inner import IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateTemplateFromInner
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate(BaseModel):
    """
    Template defines a blueprint for the created Secret resource.
    """ # noqa: E501
    data: Optional[Dict[str, StrictStr]] = None
    engine_version: Optional[StrictStr] = Field(default=None, description="EngineVersion specifies the template engine version that should be used to compile/execute the template specified in .data and .templateFrom[].", alias="engineVersion")
    metadata: Optional[IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateMetadata] = None
    template_from: Optional[List[IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateTemplateFromInner]] = Field(default=None, alias="templateFrom")
    type: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["data", "engineVersion", "metadata", "templateFrom", "type"]

    @field_validator('engine_version')
    def engine_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['v1', 'v2']):
            raise ValueError("must be one of enum values ('v1', 'v2')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in template_from (list)
        _items = []
        if self.template_from:
            for _item in self.template_from:
                if _item:
                    _items.append(_item.to_dict())
            _dict['templateFrom'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data": obj.get("data"),
            "engineVersion": obj.get("engineVersion"),
            "metadata": IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "templateFrom": [IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplateTemplateFromInner.from_dict(_item) for _item in obj["templateFrom"]] if obj.get("templateFrom") is not None else None,
            "type": obj.get("type")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


