# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_external_secret_spec_target_template import IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1alpha1ExternalSecretSpecTarget(BaseModel):
    """
    ExternalSecretTarget defines the Kubernetes Secret to be created There can be only one target per ExternalSecret.
    """ # noqa: E501
    creation_policy: Optional[StrictStr] = Field(default=None, description="CreationPolicy defines rules on how to create the resulting Secret Defaults to 'Owner'", alias="creationPolicy")
    immutable: Optional[StrictBool] = Field(default=None, description="Immutable defines if the final secret will be immutable")
    name: Optional[StrictStr] = Field(default=None, description="Name defines the name of the Secret resource to be managed This field is immutable Defaults to the .metadata.name of the ExternalSecret resource")
    template: Optional[IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["creationPolicy", "immutable", "name", "template"]

    @field_validator('creation_policy')
    def creation_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Owner', 'Merge', 'None']):
            raise ValueError("must be one of enum values ('Owner', 'Merge', 'None')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1ExternalSecretSpecTarget from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1alpha1ExternalSecretSpecTarget from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "creationPolicy": obj.get("creationPolicy"),
            "immutable": obj.get("immutable"),
            "name": obj.get("name"),
            "template": IoExternalSecretsV1alpha1ExternalSecretSpecTargetTemplate.from_dict(obj["template"]) if obj.get("template") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


