# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1beta1_secret_store_spec_provider_delinea_client_id import IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientId
from .io_external_secrets_v1beta1_secret_store_spec_provider_delinea_client_secret import IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientSecret
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1SecretStoreSpecProviderDelinea(BaseModel):
    """
    Delinea DevOps Secrets Vault https://docs.delinea.com/online-help/products/devops-secrets-vault/current
    """ # noqa: E501
    client_id: IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientId = Field(alias="clientId")
    client_secret: IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientSecret = Field(alias="clientSecret")
    tenant: StrictStr = Field(description="Tenant is the chosen hostname / site name.")
    tld: Optional[StrictStr] = Field(default=None, description="TLD is based on the server location that was chosen during provisioning. If unset, defaults to \"com\".")
    url_template: Optional[StrictStr] = Field(default=None, description="URLTemplate If unset, defaults to \"https://%s.secretsvaultcloud.%s/v1/%s%s\".", alias="urlTemplate")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["clientId", "clientSecret", "tenant", "tld", "urlTemplate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderDelinea from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of client_id
        if self.client_id:
            _dict['clientId'] = self.client_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of client_secret
        if self.client_secret:
            _dict['clientSecret'] = self.client_secret.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderDelinea from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientId": IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientId.from_dict(obj["clientId"]) if obj.get("clientId") is not None else None,
            "clientSecret": IoExternalSecretsV1beta1SecretStoreSpecProviderDelineaClientSecret.from_dict(obj["clientSecret"]) if obj.get("clientSecret") is not None else None,
            "tenant": obj.get("tenant"),
            "tld": obj.get("tld"),
            "urlTemplate": obj.get("urlTemplate")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


