# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_generators_v1alpha1_acr_access_token_spec_auth_service_principal_secret_ref_client_id import IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientId
from .io_external_secrets_generators_v1alpha1_acr_access_token_spec_auth_service_principal_secret_ref_client_secret import IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientSecret
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRef(BaseModel):
    """
    Configuration used to authenticate with Azure using static credentials stored in a Kind=Secret.
    """ # noqa: E501
    client_id: Optional[IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientId] = Field(default=None, alias="clientId")
    client_secret: Optional[IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientSecret] = Field(default=None, alias="clientSecret")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["clientId", "clientSecret"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRef from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of client_id
        if self.client_id:
            _dict['clientId'] = self.client_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of client_secret
        if self.client_secret:
            _dict['clientSecret'] = self.client_secret.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRef from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clientId": IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientId.from_dict(obj["clientId"]) if obj.get("clientId") is not None else None,
            "clientSecret": IoExternalSecretsGeneratorsV1alpha1ACRAccessTokenSpecAuthServicePrincipalSecretRefClientSecret.from_dict(obj["clientSecret"]) if obj.get("clientSecret") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


