# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_secret_store_spec_provider_kubernetes_auth_cert import IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthCert
from .io_external_secrets_v1alpha1_secret_store_spec_provider_kubernetes_auth_token import IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthToken
from .io_external_secrets_v1beta1_secret_store_spec_provider_kubernetes_auth_service_account import IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuthServiceAccount
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuth(BaseModel):
    """
    Auth configures how secret-manager authenticates with a Kubernetes instance.
    """ # noqa: E501
    cert: Optional[IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthCert] = None
    service_account: Optional[IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuthServiceAccount] = Field(default=None, alias="serviceAccount")
    token: Optional[IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthToken] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cert", "serviceAccount", "token"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cert
        if self.cert:
            _dict['cert'] = self.cert.to_dict()
        # override the default output from pydantic by calling `to_dict()` of service_account
        if self.service_account:
            _dict['serviceAccount'] = self.service_account.to_dict()
        # override the default output from pydantic by calling `to_dict()` of token
        if self.token:
            _dict['token'] = self.token.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cert": IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthCert.from_dict(obj["cert"]) if obj.get("cert") is not None else None,
            "serviceAccount": IoExternalSecretsV1beta1SecretStoreSpecProviderKubernetesAuthServiceAccount.from_dict(obj["serviceAccount"]) if obj.get("serviceAccount") is not None else None,
            "token": IoExternalSecretsV1alpha1SecretStoreSpecProviderKubernetesAuthToken.from_dict(obj["token"]) if obj.get("token") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


