# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1.29.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from .io_external_secrets_v1alpha1_secret_store_spec_retry_settings import IoExternalSecretsV1alpha1SecretStoreSpecRetrySettings
from .io_external_secrets_v1beta1_secret_store_spec_conditions_inner import IoExternalSecretsV1beta1SecretStoreSpecConditionsInner
from .io_external_secrets_v1beta1_secret_store_spec_provider import IoExternalSecretsV1beta1SecretStoreSpecProvider
from typing import Optional, Set
from typing_extensions import Self

class IoExternalSecretsV1beta1SecretStoreSpec(BaseModel):
    """
    SecretStoreSpec defines the desired state of SecretStore.
    """ # noqa: E501
    conditions: Optional[List[IoExternalSecretsV1beta1SecretStoreSpecConditionsInner]] = Field(default=None, description="Used to constraint a ClusterSecretStore to specific namespaces. Relevant only to ClusterSecretStore")
    controller: Optional[StrictStr] = Field(default=None, description="Used to select the correct ESO controller (think: ingress.ingressClassName) The ESO controller is instantiated with a specific controller name and filters ES based on this property")
    provider: IoExternalSecretsV1beta1SecretStoreSpecProvider
    refresh_interval: Optional[StrictInt] = Field(default=None, description="Used to configure store refresh interval in seconds. Empty or 0 will default to the controller config.", alias="refreshInterval")
    retry_settings: Optional[IoExternalSecretsV1alpha1SecretStoreSpecRetrySettings] = Field(default=None, alias="retrySettings")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["conditions", "controller", "provider", "refreshInterval", "retrySettings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in conditions (list)
        _items = []
        if self.conditions:
            for _item in self.conditions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['conditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of provider
        if self.provider:
            _dict['provider'] = self.provider.to_dict()
        # override the default output from pydantic by calling `to_dict()` of retry_settings
        if self.retry_settings:
            _dict['retrySettings'] = self.retry_settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IoExternalSecretsV1beta1SecretStoreSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "conditions": [IoExternalSecretsV1beta1SecretStoreSpecConditionsInner.from_dict(_item) for _item in obj["conditions"]] if obj.get("conditions") is not None else None,
            "controller": obj.get("controller"),
            "provider": IoExternalSecretsV1beta1SecretStoreSpecProvider.from_dict(obj["provider"]) if obj.get("provider") is not None else None,
            "refreshInterval": obj.get("refreshInterval"),
            "retrySettings": IoExternalSecretsV1alpha1SecretStoreSpecRetrySettings.from_dict(obj["retrySettings"]) if obj.get("retrySettings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


